### ISSUE TITLE
Compile Errors for Example3_modify_AGC_Algo

### ISSUE THREAD

**Issue by SFEMark** [sparkfun/SparkFun_Bio_Sensor_Hub_Library#2]
A [user on the forum](https://forum.sparkfun.com/viewtopic.php?f=143&t=51529&p=210084#p210084) brought up this issue with several typos in [Example 3.](https://github.com/sparkfun/SparkFun_Bio_Sensor_Hub_Library/blob/master/examples/Example3_modify_AGC_Algo/Example3_modify_AGC_Algo.ino) Here is the list of the errors with fixes:

- L65: `int error = bioHub.setAlgoRange(algoRange));`
- L86: `int algoVal = bioHub.readAlgoRange());`
- L90 `int stepVal = bioHub.readAlgoStepSize());`
- L94 `int senVal = bioHub.readAlgoSensitivity());`
- L98 `int sampVal = bioHub.readAlgoSamples());`

All of these lines just have one extra bracket after the function call. Editing to remove the extra bracket is all that is needed.

- L103 error = configBpm(MODE_ONE);

This does not have a call to bioHub prior to the configBpm function. Modifying to `bioHub.configBpm(MODE_ONE);` fixes the error.

Can we get this example updated and, if necessary, push a new version of the library with these fixes? Thanks!

**Comment by edspark** [comment]
Fixed, thanks Mark!

Commit: https://github.com/sparkfun/SparkFun_Bio_Sensor_Hub_Library/commit/577a561f84a5c9650186982ad34dfae9bde02de2
Release: https://github.com/sparkfun/SparkFun_Bio_Sensor_Hub_Library/releases/tag/v1.0.2
