### ISSUE TITLE
Automatic Gain Control (AGC)  without MAX32664 Bio Metric Sensor Hub 

### ISSUE THREAD

**Issue by williamesp2015** [sparkfun/SparkFun_Bio_Sensor_Hub_Library#22]
It is really great example (Example 3) to find Gain Control automatically, but is there any try to do it without MAX32664 Bio Metric Sensor Hub ?

**Comment by edspark** [comment]
No I don't believe there is. The Bio Sensor Hub has proprietary firmware that breaks out certain adjustments to its calculations but you could not say impose some sort of analog filtering without it.
