### ISSUE TITLE
Confidence levels

### ISSUE THREAD

**Issue by lambo81** [sparkfun/SparkFun_Bio_Sensor_Hub_Library#23]
I have looked at the max32664 and max30101 datasheets, and I did not find anything about the confidence level and how to use it.

Can someone please explain the confidence level such as the min and max values, and any other information about it?  Originally I thought it might be 0-100, but I have received confidence levels over 100.  Right now I am arbitrarily discarding readings with confidence below 90.  Please help.

**Comment by edspark** [comment]
That is strange, the confidence level should not exceed 100. If you have any interest in this all this time later then please add more information. Seeing as this library has been around for a while and I have not seen other issues regarding the confidence value, then I will close this issue.
