### ISSUE TITLE
Bad pointer passing

### ISSUE THREAD

**Issue by arabine** [sparkfun/SparkFun_Bio_Sensor_Hub_Library#3]
Hello,

Please correct this whole function: getBootloaderInf(), it does not pass GCC build, especially this line:

`
int32_t* revNum;
readMultipleBytes(BOOTLOADER_INFO, BOOTLOADER_VERS, 0x00, 4, revNum); 
`

**Comment by edspark** [comment]
Thanks for the post - I'll take a look at this as soon as I'm able.

**Comment by edspark** [comment]
Agreed, and fixed in the latest [pull request](https://github.com/sparkfun/SparkFun_Bio_Sensor_Hub_Library/pull/17).
