### ISSUE TITLE
problems with ADC Range

### ISSUE THREAD

**Issue by alexmstahl** [sparkfun/SparkFun_Bio_Sensor_Hub_Library#4]
1) bitmasks ADC_MASK and READ_ADC_MASK are incorrectly defined. They are defined as 0x3F and 0xC0. They should be 0x9F and 0x60.

2)in the function setAdcRange, there is a missing bit shift:
the line
 regVal |= adcVal;
should be 
 regVal |= (bits << 5);

**Comment by edspark** [comment]
Absolutely right, fixed [here](https://github.com/sparkfun/SparkFun_Bio_Sensor_Hub_Library/releases/tag/v1.0.3)!
