### ISSUE TITLE
ARDUINO LIBRARY FOR MAX30101 VERSION D FOR MEASURING BLOOD PRESSURE

### ISSUE THREAD

**Issue by parminder4499** [sparkfun/SparkFun_Bio_Sensor_Hub_Library#9]
I am using sparkfun's spo2 sensor board(MAX30101 version A) for measuring spo2 and heart rate. I want to measure blood pressure as well from MAX30101 version D which has firmware by MAXIM integrated for measuring BP. I hereby wanted to ask you if you can modify the Arduino library for MAX30101 version A, so that it can also measures Blood pressure when using version D of the sensor?
If that library is build up then we can freely use MAX30101's different versions for making products using sparkfun's library.
Thanks

**Comment by santaimpersonator** [comment]
Duplicate issue. See: https://github.com/sparkfun/SparkFun_Bio_Sensor_Hub_Library/issues/10

Also closing.

**Comment by edspark** [comment]
After looking through the datasheet, this could be done in an afternoon. I'll try to add it soon.

**Comment by edspark** [comment]
Added in latest [pull request](https://github.com/sparkfun/SparkFun_Bio_Sensor_Hub_Library/pull/17), I may have to do some additional tweaking but the functions are there.
